### ISSUE TITLE
Disable Rollback button not working

### ISSUE THREAD

**Issue by stephenmsachs** [aws-samples/pcluster-manager#270]
When I deploy clusters through PCM and enable the 'Disable Rollback' button, the cfn stacks are still created with `"DisableRollback": false`.

**Comment by mendaomn** [comment]
Can you share the full yaml configuration? It could help us investigate the problem, thank you

**Comment by stephenmsachs** [comment]
Cluster configuration as reported by PCM:
```
HeadNode:
  InstanceType: hpc6a.48xlarge
  Ssh:
    KeyName: isengard
  Networking:
    SubnetId: subnet-xxxxxxxxx
  LocalStorage:
    RootVolume:
      VolumeType: gp3
      Size: 500
  CustomActions:
    OnNodeStart:
      Script: s3://xxxxxxxxxxxx
  Iam:
    S3Access:
      - EnableWriteAccess: true
        BucketName: '*'
    AdditionalIamPolicies: []
Scheduling:
  Scheduler: slurm
  SlurmQueues:
    - Name: queue0
      ComputeResources:
        - Name: queue0-hpc6a48xlarge
          MinCount: 0
          MaxCount: 4
          InstanceType: hpc6a.48xlarge
          Efa:
            Enabled: true
            GdrSupport: true
      Networking:
        SubnetIds:
          - subnet-xxxxxxxxxxx
        PlacementGroup:
          Enabled: true
      ComputeSettings:
        LocalStorage:
          RootVolume:
            VolumeType: gp3
Region: us-east-2
Image:
  Os: alinux2
```
