### ISSUE TITLE
Cluster cannot be deleted after failed build

### ISSUE THREAD

**Issue by stephenmsachs** [aws-samples/pcluster-manager#279]
I have added custom IAM policies to the compute fleet via the fee text form. This resulted in the CFN stack failing due to insufficient IAM privileges. So far this is expected.

The automatic rollback of the cluster now also failed with:

``` shell
API: iam:DetachRolePolicy User: arn:aws:sts::679174810898:assumed-role/pcluster-manager-ParallelC-ParallelClusterUserRole-RKG33ZCX2WF0/pcluster-manager-ParallelC-ParallelClusterFunction-Nm3OFUJX0al9 is not authorized to perform: iam:DetachRolePolicy on resource: role test-create-failed-Role92c955f11741866e-16EOE8EVK1CKX because no identity-based policy allows the iam:DetachRolePolicy action
```

The full cluster configuration is:

``` yaml
HeadNode:
  InstanceType: hpc6a.48xlarge
  Ssh:
    KeyName: isengard
  Networking:
    SubnetId: subnet-xxxxx
  LocalStorage:
    RootVolume:
      VolumeType: gp3
      Size: 500
  CustomActions:
    OnNodeStart:
      Script: s3://xxxxx
  Iam:
    S3Access:
      - EnableWriteAccess: true
        BucketName: '*'
    AdditionalIamPolicies: []
Scheduling:
  Scheduler: slurm
  SlurmQueues:
    - Name: queue0
      ComputeResources:
        - Name: queue0-hpc6a48xlarge
          MinCount: 0
          MaxCount: 4
          InstanceType: hpc6a.48xlarge
          Efa:
            Enabled: true
            GdrSupport: true
      Networking:
        SubnetIds:
          - subnet-xxxxxx
        PlacementGroup:
          Enabled: true
      ComputeSettings:
        LocalStorage:
          RootVolume:
            VolumeType: gp3
      Iam:
        AdditionalIamPolicies:
          - Policy: arn:aws:iam::aws:policy/AmazonS3FullAccess
Region: us-east-2
Image:
  Os: alinux2
```
