### ISSUE TITLE
Private-only subnet clusters do not allow Remote Console

### ISSUE THREAD

**Issue by bollig** [aws-samples/pcluster-manager#31]
![image](https://user-images.githubusercontent.com/187202/155563939-9d0d77f0-672c-495b-87f1-d7791bd5da4a.png)

Related to #29 ?

**Comment by bollig** [comment]
```
HeadNode:
  InstanceType: t2.micro
  Ssh:
    KeyName: YYYYYYYYYYY
  Networking:
    SubnetId: subnet-YYYYYYYYYYY
    AdditionalSecurityGroups:
       - sg-YYYYYYYYYYY
  Iam:
    AdditionalIamPolicies:
      - Policy: arn:aws-us-gov:iam::aws:policy/AmazonSSMManagedInstanceCore
  Dcv:
    Enabled: true
  LocalStorage:
    RootVolume:
      Size: 100
Scheduling:
  Scheduler: slurm
  SlurmSettings:
    Dns:
      DisableManagedDns: true
      UseEc2Hostnames: true
  SlurmQueues:
    - Name: queue0
      ComputeResources:
        - Name: queue0-t2-micro
          MinCount: 0
          MaxCount: 4
          InstanceType: t2.micro
      Networking:
        SubnetIds:
          - subnet-YYYYYYYYYYY
        AdditionalSecurityGroups:
          - sg-YYYYYYYYYYY
Region: us-gov-west-1
Image:
  Os: alinux2
SharedStorage:
  - Name: Efs0
    StorageType: Efs
    MountDir: /data
    EfsSettings:
      ThroughputMode: bursting
      Encrypted: false
  - Name: FsxLustre1
    StorageType: FsxLustre
    MountDir: /fsx
    FsxLustreSettings:
      StorageCapacity: 1200
      DeploymentType: SCRATCH_2
  - Name: Ebs2
    StorageType: Ebs
    MountDir: /shared
    EbsSettings:
      VolumeType: gp2
      DeletionPolicy: Delete
      Size: 35
```
