### ISSUE TITLE
Create Pcluster Manager Fails

### ISSUE THREAD

**Issue by sean-smith** [aws-samples/pcluster-manager#366]
Hi,

Using the following cluster template breaks the create interface after the Storage Tab with:

<img width="1025" alt="image" src="https://user-images.githubusercontent.com/5545980/201721185-1306eac8-11c2-4d37-aa80-916256a16d88.png">

From the Chrome console I see: 

```bash
framework-bb5c596eafb42b22.js:1 TypeError: Cannot read properties of undefined (reading 'length')
    at index-e0a78d528f2085ff.js:1:170318
    at Array.filter (<anonymous>)
    at index-e0a78d528f2085ff.js:1:170289
    at _a (index-e0a78d528f2085ff.js:1:170339)
    at oo (framework-bb5c596eafb42b22.js:1:59416)
    at Ku (framework-bb5c596eafb42b22.js:1:111716)
    at Li (framework-bb5c596eafb42b22.js:1:98957)
    at Ni (framework-bb5c596eafb42b22.js:1:98885)
    at Pi (framework-bb5c596eafb42b22.js:1:98748)
    at bi (framework-bb5c596eafb42b22.js:1:95714)
cu @ framework-bb5c596eafb42b22.js:1
main-1ae0bdeb4d020668.js:1 TypeError: Cannot read properties of undefined (reading 'length')
    at index-e0a78d528f2085ff.js:1:170318
    at Array.filter (<anonymous>)
    at index-e0a78d528f2085ff.js:1:170289
    at _a (index-e0a78d528f2085ff.js:1:170339)
    at oo (framework-bb5c596eafb42b22.js:1:59416)
    at Ku (framework-bb5c596eafb42b22.js:1:111716)
    at Li (framework-bb5c596eafb42b22.js:1:98957)
    at Ni (framework-bb5c596eafb42b22.js:1:98885)
    at Pi (framework-bb5c596eafb42b22.js:1:98748)
    at bi (framework-bb5c596eafb42b22.js:1:95714)
ee @ main-1ae0bdeb4d020668.js:1
main-1ae0bdeb4d020668.js:1 A client-side exception has occurred, see here for more info: https://nextjs.org/docs/messages/client-side-exception-occurred
```

Here's the template that broke it, with some params changed:

```yaml
Region: us-east-2
Image:
  Os: alinux2
HeadNode:
  InstanceType: c6i.2xlarge
  Networking:
    SubnetId: subnet-123456789
  Ssh:
    KeyName: keypair
  DisableSimultaneousMultithreading: true
  LocalStorage:
    RootVolume:
      Size: 100
      VolumeType: gp3
  CustomActions:
    OnNodeConfigured:
      Script: >-
        https://bucket.us-east-2.amazonaws.com/headnode_install.sh
      Args:
        - HEAD
  Iam:
    AdditionalIamPolicies:
      - Policy: arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
  Dcv:
    Enabled: true
Scheduling:
  Scheduler: slurm
  SlurmQueues:
    - Name: compute
      CapacityType: ONDEMAND
      ComputeResources:
        - Name: compute-hpc6a
          Efa:
            Enabled: true
            GdrSupport: true
          InstanceType: hpc6a.48xlarge
          MinCount: 0
          MaxCount: 101
          DisableSimultaneousMultithreading: true
      Networking:
        SubnetIds:
          - subnet-123456789
        PlacementGroup:
          Enabled: true
      CustomActions:
        OnNodeConfigured:
          Script: >-
            https://bucket.s3.us-east-2.amazonaws.com/compute_install.sh
      ComputeSettings:
        LocalStorage:
          RootVolume:
            VolumeType: gp3
SharedStorage:
  - MountDir: /opt/ncar
    Name: ncar
    StorageType: Ebs
    EbsSettings:
      Size: '35'
      VolumeType: gp3
      DeletionPolicy: Delete
  - MountDir: /scratch
    Name: scratch
    StorageType: FsxLustre
    FsxLustreSettings:
      FileSystemId: fs-0e709f43fbde2c3a2
```
