### ISSUE TITLE
efa for hpc6a

### ISSUE THREAD

**Issue by bollig** [aws-samples/pcluster-manager#7]
Need to enable Efa toggle for hpc6a; toggle is also disabled for c5n.9xlarge and other [supported instance types](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/efa.html#efa-instance-types)
```
        - Name: queue0-hpc6a24xlarge
          MinCount: 0
          MaxCount: 10
          InstanceType: hpc6a.48xlarge
          DisableSimultaneousMultithreading: true
          Efa:
            Enabled: true
```
